# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Extract indices of parameters related to the IRT model
#'
#' `THETA_IRT` is assumed to be ordered as follows
#' c(exam1_int, exam1_slope, exam1_time_loc, exam1, time_sca, exam2_int, ...)
#'
#' @param THETA_IRT parameter vector related to irt model
#' @param N_GRADES number of grades modelled.
#' @param N_EXAMS number of exams.
#' @param OPTION Select parameters of interest. `1` for exam-grades slopes,
#' `2` for exam-grade intercepts, `3` for time-location parameter,
#' `4` for time-scale parameter.
#' @param EXAM exam of interest. Possible values in `0:(N_EXAMS-1)`.
#'
#' @returns It return a vector with two values representing the starting
#' index and the length of the segment of THETA_IRT corresponding to
#' the parameter of interest.
#'
#' @export
extract_params_idx_irt <- function(THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM) {
    .Call(`_crirt_extract_params_idx_irt`, THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM)
}

#' Extract parameters related to the IRT model
#'
#' See [extract_params_idx_irt]
#' @param THETA_IRT parameter vector related to irt model
#' @param N_GRADES number of grades modelled.
#' @param N_EXAMS number of exams.
#' @param OPTION Select parameters of interest. `1` for exam-grades slopes,
#' `2` for exam-grade intercepts, `3` for time-location parameter,
#' `4` for time-scale parameter.
#' @param EXAM exam of interest. Possible values in `1:N_EXAMS`.
#' @export
extract_params_irt <- function(THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM) {
    .Call(`_crirt_extract_params_irt`, THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM)
}

#' IRT complete observation
#'
#' Evaluate the IRT complete model log likelihood of a single observation
#'
#' @param THETA Suitable parameter vector as provided by [parList2Vec]
#' @param EXAMS_GRADES Vector of grades.
#' @param EXAMS_DAYS Vector of times.
#' @param EXAMS_OBSFLAG Vector of booleans.`TRUE` elements represent observed exams. `FALSE` elements the unobserved ones.
#' @param EXAMS_SET Vector filled with booleans.`TRUE` elements represent exams in the study plan. `FALSE` elements non-relevant ones.
#' @param MAX_DAY Last day of observation
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams modelled
#' @param ABILITY Ability value.
#' @param SPEED Speed value.
#'
#' @return It returns the value of the integrand function,
#' given the parameters and the data of a single observation.
#'
#' @export
GRTCM_complete_obs <- function(THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_OBSFLAG, EXAMS_SET, COVARIATES, MAX_DAY, N_GRADES, N_EXAMS, ABILITY, SPEED) {
    .Call(`_crirt_GRTCM_complete_obs`, THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_OBSFLAG, EXAMS_SET, COVARIATES, MAX_DAY, N_GRADES, N_EXAMS, ABILITY, SPEED)
}

#' @export
CRGRTCM_complete_obs <- function(THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_OBSFLAG, EXAMS_SET, OUTCOME, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, COVARIATES, MAX_DAY, YB, N_GRADES, N_EXAMS, ABILITY, SPEED) {
    .Call(`_crirt_CRGRTCM_complete_obs`, THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_OBSFLAG, EXAMS_SET, OUTCOME, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, COVARIATES, MAX_DAY, YB, N_GRADES, N_EXAMS, ABILITY, SPEED)
}

#' @export
CCR <- function(THETA, OUTCOME, COVARIATES, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, LATMAT, YB, GRFLAG) {
    .Call(`_crirt_CCR`, THETA, OUTCOME, COVARIATES, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, LATMAT, YB, GRFLAG)
}

#' @export
cpp_EM <- function(THETA_START, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, OUTCOME, EXT_COVARIATES, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, GRID, WEIGHTS, YB, N_GRADES, N_EXAMS, M_MAX_ITER, MAX_ITER, TOL, MOD, VERBOSE) {
    .Call(`_crirt_cpp_EM`, THETA_START, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, OUTCOME, EXT_COVARIATES, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, GRID, WEIGHTS, YB, N_GRADES, N_EXAMS, M_MAX_ITER, MAX_ITER, TOL, MOD, VERBOSE)
}

#' @export
cpp_GQ <- function(THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, COVARIATES, MAX_DAY, OUTCOME, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, GRID, WEIGHTS, N_GRADES, N_EXAMS, YB, MOD, GRFLAG = TRUE, LATPARFLAG = TRUE, HFLAG = FALSE) {
    .Call(`_crirt_cpp_GQ`, THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, COVARIATES, MAX_DAY, OUTCOME, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, GRID, WEIGHTS, N_GRADES, N_EXAMS, YB, MOD, GRFLAG, LATPARFLAG, HFLAG)
}

#' @export
cpp_EAP <- function(THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, OUTCOME, EXT_COVARIATES, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, GRID, WEIGHTS, YB, N_GRADES, N_EXAMS, MOD, VERBOSE) {
    .Call(`_crirt_cpp_EAP`, THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, OUTCOME, EXT_COVARIATES, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, GRID, WEIGHTS, YB, N_GRADES, N_EXAMS, MOD, VERBOSE)
}

#' @export
cpp_pGreaterGrades <- function(GRADE, EXAM, THETA, COVARIATES, N_GRADES, N_EXAMS, ABILITY, LOGFLAG, LATPARFLAG) {
    .Call(`_crirt_cpp_pGreaterGrades`, GRADE, EXAM, THETA, COVARIATES, N_GRADES, N_EXAMS, ABILITY, LOGFLAG, LATPARFLAG)
}

#' @export
cpp_pGrade <- function(GRADE, EXAM, THETA, COVARIATES, N_GRADES, N_EXAMS, ABILITY, LOGFLAG, LATPARFLAG) {
    .Call(`_crirt_cpp_pGrade`, GRADE, EXAM, THETA, COVARIATES, N_GRADES, N_EXAMS, ABILITY, LOGFLAG, LATPARFLAG)
}

#' @export
cpp_pTimeExam <- function(EXAM, DAY, THETA, COVARIATES, N_GRADES, N_EXAMS, SPEED, ABILITY, CDFFLAG, LOGFLAG, LATPARFLAG) {
    .Call(`_crirt_cpp_pTimeExam`, EXAM, DAY, THETA, COVARIATES, N_GRADES, N_EXAMS, SPEED, ABILITY, CDFFLAG, LOGFLAG, LATPARFLAG)
}

#' @export
cpp_examLik <- function(EXAM, GRADE, DAY, MAX_DAY, OBSFLAG, THETA, COVARIATES, N_GRADES, N_EXAMS, ABILITY, SPEED, LATPARFLAG) {
    .Call(`_crirt_cpp_examLik`, EXAM, GRADE, DAY, MAX_DAY, OBSFLAG, THETA, COVARIATES, N_GRADES, N_EXAMS, ABILITY, SPEED, LATPARFLAG)
}

#' @export
cpp_grtcm_class <- function(THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, COVARIATES, ABILITY, SPEED, MAX_DAY, N_GRADES, N_EXAMS, LATPARFLAG) {
    .Call(`_crirt_cpp_grtcm_class`, THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, COVARIATES, ABILITY, SPEED, MAX_DAY, N_GRADES, N_EXAMS, LATPARFLAG)
}

#' @export
cpp_survival <- function(YEAR_FIRST, YEAR_LAST, THETA, COVARIATES, ABILITY, SPEED, YB, YEAR_LAST_EXAM, LATPARFLAG) {
    .Call(`_crirt_cpp_survival`, YEAR_FIRST, YEAR_LAST, THETA, COVARIATES, ABILITY, SPEED, YB, YEAR_LAST_EXAM, LATPARFLAG)
}

#' @export
cpp_hazard <- function(OUTCOME, YEAR, THETA, COVARIATES, ABILITY, SPEED, YB, LATPARFLAG = FALSE) {
    .Call(`_crirt_cpp_hazard`, OUTCOME, YEAR, THETA, COVARIATES, ABILITY, SPEED, YB, LATPARFLAG)
}

#' @export
cpp_outcome <- function(OUTCOME, YEAR_FIRST, YEAR_LAST, THETA, COVARIATES, ABILITY, SPEED, YB, YEAR_LAST_EXAM, LATPARFLAG) {
    .Call(`_crirt_cpp_outcome`, OUTCOME, YEAR_FIRST, YEAR_LAST, THETA, COVARIATES, ABILITY, SPEED, YB, YEAR_LAST_EXAM, LATPARFLAG)
}

#' @export
cpp_cr_class <- function(OUTCOME, YEAR_FIRST, YEAR_LAST, THETA, COVARIATES, ABILITY, SPEED, YB, YEAR_LAST_EXAM, LATPARFLAG) {
    .Call(`_crirt_cpp_cr_class`, OUTCOME, YEAR_FIRST, YEAR_LAST, THETA, COVARIATES, ABILITY, SPEED, YB, YEAR_LAST_EXAM, LATPARFLAG)
}

#' @export
cpp_lat <- function(THETA, COVARIATES, ABILITY, SPEED) {
    .Call(`_crirt_cpp_lat`, THETA, COVARIATES, ABILITY, SPEED)
}

#' @export
cpp_estep <- function(THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, OUTCOME, EXT_COVARIATES, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, GRID, WEIGHTS, YB, N_GRADES, N_EXAMS, MOD) {
    .Call(`_crirt_cpp_estep`, THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, OUTCOME, EXT_COVARIATES, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, GRID, WEIGHTS, YB, N_GRADES, N_EXAMS, MOD)
}

#' @export
cpp_mstep2 <- function(THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, OUTCOME, EXT_COVARIATES, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, GRID, EWEIGHTS, YB, N_GRADES, N_EXAMS, MOD) {
    .Call(`_crirt_cpp_mstep2`, THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, OUTCOME, EXT_COVARIATES, YEAR_FIRST, YEAR_LAST, YEAR_LAST_EXAM, GRID, EWEIGHTS, YB, N_GRADES, N_EXAMS, MOD)
}

#' Intercepts reparameterisation
#'
#' @param X Intercepts or unconstrained parameter values for grades low-to-high.
#' @param CON2UN TRUE if going from the constrained space to the unconstrained one.
#'
#' @returns It allows to go back and forth from constrained intercepts
#' to unconstrained parameters.
#'
#' @export
reparThr <- function(X, CON2UN = FALSE) {
    .Call(`_crirt_reparThr`, X, CON2UN)
}

